version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup-main:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/main.yml
      - when:
        condition:
          equal: [ main, << pipeline.git.branch >> ]
  setup-dev:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/dev.yml
      - when:
        matched:
          pattern: "^deploy/pfdev-review$"
          value: << pipeline.git.branch >>

workflows:
  run-main:
    jobs:
      - setup-main
      - setup-dev