version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  kick-main:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/main.yml
      - when:
        condition:
          equal: [ main, << pipeline.git.branch >> ]
  kick-dev:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/develop.yml
      - when:
        condition:
          matched:
            pattern: "^deploy/pfdev-review$"
            value: << pipeline.git.branch >>

workflows:
  run-main:
    jobs:
      - kick-main
      - kick-dev