version: 2.1

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  run-main:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/main.yml
  run-dev:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/develop.yml

workflows:
  run-main:
    jobs:
      - run-main
    when:
      condition:
        equal: [ main, << pipeline.git.branch >> ]
  run-dev:
    jobs:
      - run-dev
    when:
      matched:
        pattern: "^deploy/pfdev-review$"
        value: << pipeline.git.branch >>