version: 2.1

setup: true
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    environment:
      TARGET_FILE: ./circleci/main.yml
    steps:
      - checkout
      - run:
          command: |
            echo "${CIRCLE_BRANCH}"
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              export TARGET_FILE="./circleci/main.yml"
            else
              export TARGET_FILE="./circleci/develop.yml"
            fi
      - run:
          command: |
            echo "${TARGET_FILE}"
      - continuation/continue:
          configuration_path: TARGET_FILE

workflows:
  setup:
    jobs:
      - setup