version: 2.1

setup: true
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            echo "${CIRCLE_BRANCH}"
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              export TARGET_FILE="./circleci/main.yml" >> $BASH_ENV
            else
              export TARGET_FILE="./circleci/develop.yml" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          command: |
            echo "${BASH_ENV}"
      - continuation/continue:
          configuration_path: ${TARGET_FILE}

workflows:
  setup:
    jobs:
      - setup