version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  kick-main:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              cp .circleci/main.yml run.yml
            else
              cp .circleci/develop.yml run.yml
            fi
      - continuation/continue:
          configuration_path: ./run.yml

workflows:
  run-main:
    jobs:
      - kick-main