version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  kick-main:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command:
            if [[ "${CIRCLE_BRANCH}" == "main" ]]
            then
              .circleci/main.yml > run.yml
            else then
              .circleci/develop.yml > run.yml
            fi
      - continuation/continue:
          configuration_path: .circleci/run.yml
  # kick-dev:
  #   executor: continuation/default
  #   steps:
  #     - checkout
  #     - continuation/continue:
  #         configuration_path: .circleci/develop.yml
  #     - when:
  #       condition:
  #         matched:
  #           pattern: "^deploy/pfdev-review$"
  #           value: << pipeline.git.branch >>

workflows:
  run-main:
    jobs:
      - kick-main
      # - kick-dev