version: 2.1

executors:
  default-executor:
    resource_class: medium

    docker:
      - image: circleci/node:12

jobs:
  main:
    executor: default-executor
    steps:
      - checkout
      - run:
          command: |
            echo "main"
      - run:
          command: |
            echo $CIRCLE_BRANCH

workflows:
  run-main:
    jobs:
      - main