version: 2.1

executors:
  default-executor:
    resource_class: medium

    docker:
      - image: circleci/node:12

jobs:
  main:
    executor: default-executor
    steps:
      - checkout
      - run:
          command: |
            echo "main"
      - run:
          command: |
            echo $CIRCLE_BRANCH
      - run:
          command: |
            curl -u ${TO_AMAZON2_CIRCLECI_API_TOKEN}: -X POST --header "Content-Type: application/json" -d '{ \
              "parameters": {}, \
              "branch": "main" \
            }' https://circleci.com/api/v2/project/gh/shukubota/amazonlinux2-sandbox/pipeline

workflows:
  run-main:
    jobs:
      - main